name: test-build

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install packages
        run: npm install
      - name: Build website
        run: npm run build
